# Generated by Django 3.2.4 on 2021-06-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teammate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('birth', models.DateField()),
                ('live', models.CharField(max_length=20)),
                ('birthlocation', models.CharField(max_length=20)),
                ('major', models.CharField(max_length=50)),
                ('food', models.CharField(max_length=20)),
                ('haslover', models.CharField(max_length=20)),
                ('number', models.CharField(max_length=20)),
                ('alchol', models.CharField(max_length=20)),
                ('dream', models.TextField()),
            ],
        ),
    ]
