# Generated by Django 3.2.4 on 2021-06-29 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210628_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='Todr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='adSp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='anCn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='chCn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='cmdr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='dedr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='dgsb',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='emCn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='emDy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='emNg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='hgSi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='isCn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='medr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='nbSp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='paCn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='paQt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='pshgCn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='psstCn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='ptCn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='soCn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='srch',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='stSi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
