# Generated by Django 3.2.3 on 2021-05-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=20)),
                ('where', models.CharField(max_length=50)),
                ('period', models.IntegerField(blank=True)),
                ('day', models.CharField(max_length=10)),
                ('time', models.TimeField(blank=True)),
                ('pay', models.IntegerField(blank=True)),
                ('detail', models.TextField()),
                ('valunteer', models.IntegerField(default=0)),
            ],
        ),
    ]
