# Generated by Django 3.2.3 on 2021-05-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='pay',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='period',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='time',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
