# Generated by Django 3.2.3 on 2021-05-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_auto_20210523_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='pay',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='period',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='time',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
