# Generated by Django 3.2.3 on 2021-05-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_auto_20210523_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='pay',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='period',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
