# Generated by Django 3.2.4 on 2021-06-19 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='imgae',
            new_name='image',
        ),
    ]
